# Generated by Django 5.2 on 2025-05-01 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MT5Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.IntegerField(unique=True)),
                ('broker', models.CharField(max_length=100)),
                ('token', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'MT5 Account',
                'verbose_name_plural': 'MT5 Accounts',
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.IntegerField()),
                ('symbol', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('volume', models.FloatField()),
                ('entry_price', models.FloatField()),
                ('exit_price', models.FloatField()),
                ('profit', models.FloatField()),
                ('swap', models.FloatField()),
                ('commission', models.FloatField()),
                ('entry_time', models.DateTimeField()),
                ('exit_time', models.DateTimeField()),
                ('duration', models.DurationField()),
                ('magic_number', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='trading.mt5account')),
            ],
        ),
    ]
