# Generated by Django 5.2 on 2025-05-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربران'},
        ),
        migrations.AddField(
            model_name='user',
            name='api_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='توکن API'),
        ),
        migrations.AddField(
            model_name='user',
            name='broker_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام بروکر'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_trader',
            field=models.BooleanField(default=False, verbose_name='معامله گر؟'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, verbose_name='شماره تلفن'),
        ),
    ]
